---

- name: Configure client package (apt) mirrors
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  gather_facts: true

  # roles:
  #   - role: config_client_ubuntu_mirror
  #     when: "'ubuntu' in client_mirror_profiles"

  #   - role: config_client_docker_mirror
  #     when: "'docker_ce' in client_mirror_profiles"

  #   - role: config_client_external_sources
  #     when: config_client_external_sources_enabled | default(false) | bool

  tasks:

    - name: Configure Ubuntu client for local package (apt) server
      ansible.builtin.include_role:
        name: "dperr.linux.config_ubuntu_mirrors"
